name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_HOOK_URL: ${{secrets.WEB_HOOK_URL}}
      MAIL_HOST: ${{secrets.MAIL_HOST}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      KAKAO_REST_API_KEY: ${{secrets.KAKAO_REST_API_KEY}}
      KAKAO_REST_API_URI: ${{secrets.KAKAO_REST_API_URI}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      
      - name: Grant executepermission for gradlew
        run: ./gradlew build
        shell: bash
