name: CICD

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    env:
      MAIL_HOST: ${{secrets.MAIL_HOST}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      KAKAO_REST_API_KEY: ${{secrets.KAKAO_REST_API_KEY}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew test

      - name: run build
        run: ./gradlew clean build -x test

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SLACK_WEBHOOK_URL: ${{secrets.BUILD_SLACK_WEBHOOK_URL}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run build
        run: ./gradlew clean build -x test

      - name: Build Docker Image
        run: docker build -t rkdtlsgml40/dmeista:latest .

      - name: Publish To Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rkdtlsgml40/dmeista:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Action slack
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: GitHub Actions Build Result
