name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_HOOK_URL: ${{secrets.WEB_HOOK_URL}}
      MAIL_HOST: ${{secrets.MAIL_HOST}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      KAKAO_REST_API_KEY: ${{secrets.KAKAO_REST_API_KEY}}
      KAKAO_REST_API_URI: ${{secrets.KAKAO_REST_API_URI}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SLACK_WEBHOOK_URL: ${{secrets.BUILD_SLACK_WEBHOOK_URL}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      
      - name: Build Gradle
        run: ./gradlew build
        shell: bash
        
      - name: Build Docker Image
        run: docker build -t rkdtlsgml40/dmeista:latest .

      - name: Action slack
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: GitHub Actions Build Result

      - name: Publish To Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rkdtlsgml40/dmeista:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
