name: CI CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Test
        run: ./gradlew test

      - name: Run Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Jar
          path: build/libs

  CD:
    runs-on: ubuntu-latest
    needs: CI

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SLACK_WEBHOOK_URL: ${{secrets.BUILD_SLACK_WEBHOOK_URL}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: Jar

      - name: Build DockerImage
        run: docker build -t rkdtlsgml40/dmeista:latest .

      - name: Publish To Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rkdtlsgml40/dmeista:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Action slack
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: GitHub Actions Build Result
